### PR TITLE
Minor refactoring on errors, improving code reuse.

### PR DESCRIPTION
**Pull request by tinchodias**
This PR changes some error classes I recently introduced, that deserve to share a common abstract superclass.

### CODE REVIEW

**Comment by tinchodias** [comment]
This PR is still valid. it's code enhancement. Do we merge it? (I forgot about it!)

**Comment by estebanlm** [comment]
esto tiene conflictos a resolver :(

**Comment by estebanlm** [comment]
but this is super old... it is worthy still?

**Comment by tinchodias** [comment]
Frankly I didn't remember well, but I loaded and browsed the PR and it was good idea and simple.

The PR seems up-to-date: 

- Tests run
- Checked the log of the filetree directories of the 3 error classes involved: no other changes were made into those classes. 

=> I rebased in a new branch (PR #25). Please check ;-)

**Pull request closed without merging**
