### PR TITLE
Add support for OrderedDictionary

### PR DESCRIPTION
**Pull request by zecke**
In Pharo3 code like:

db command: {
	'createIndexes' -> 'collectionName'.
		'indexes' -> {
         {
   				'key' -> {
					'field1' -> 1.
					'field2' -> 2.
            } asDictionary.
			...

was used but with Pharo6 the dictionary gets written as field2, field1 and then causes an issue. Start using and supporting asOrderedDictionary to keep the order. Add the necessary BSON definitions to support it.

### CODE REVIEW

**Comment by zecke** [comment]
@noha @estebanlm: This would require Pharo4. What are other options?

**Comment by krodelin** [comment]
@zecke: I'm normally using `SmallDictionary` in cases where I need a dictionary with specific key order. Can you check if
a) Your Pharo version provides a `SmallDictionary` and
b) if it retains the order of keys?

**Comment by zecke** [comment]
@krodelin My issue with using it, is the absence of asSmallDictionary (and that I didn't feel like rewriting my initialization code).

But if your argument is that saving an OrderedDictionary and getting something else back, you might have a point. ;)

**Comment by noha** [comment]
There are multiple issues here. First Mongo "uses" BSON but for several commands there is a constraint about the ordering of the keys. So it could be a good thing to make ordered dictionary the default. The only incarnation of an ordered dictionary was SmallDictionary. Although not the best choice the one that worked. I've changed mongotalk for that in order to be able to invoke constraint commands in mongo. Now we have OrderDictionary in pharo6. As we want to support older versions of pharo this fix cannot be applied because it would tie it to modern pharos only. The proper way of doing this is to make a pharo6 extension package in mongotalk and change metacello to load that package in case of pharo6. 
Furthermore I don't like this change because it changes an awful lot of method authorship and timestamp for no reason. And I don't like an author named "guest". 
So my advize is not to integrate that change

**Comment by noha** [comment]
Any updates?

**Comment by mikefilonov** [comment]
In #21 I added new class "CommandOperation" which expects for "where" statement of the query to be an Ordered Dictionary and calls to "BSON writer nextOrderedDictionaryPut:" directly:

```
CommandOperation>>computeDataBytes
	^BSON writer 
		nextOrderedDictionaryPut: mongoQuery where; 
		contents
```

In change #22 I changed calls to command to use the following syntax:

```
database command: (OrderedIdentityDictionary new
			at: #getnonce put: 1;
  			yourself)
```
The alternative syntax could be:
```
database command: (OrderedIdentityDictionary newFrom: { #isMaster -> 1 })
```
OrderedDictionary also seems to work fine.

This two PR solve the issue and they work on Pharo 3 to 6. Also the support of OrderedDictionary comes with existing BSON method and applied only to command (so other queries preserve ad-hoc sort with "_id" to be the first field).

This PR can be discarded?

P.S. I like the following syntax though...
```
{ #update->name. updates->"..." } asOrderedDictionary.
```

**Pull request merged**
