### PR TITLE
Introduce writeConcern and related error handling

### PR DESCRIPTION
**Pull request by zecke**

### CODE REVIEW

**Comment by tinchodias** [comment]
This PR includes #18. @zecke Do you think it's better to merge them in 2 steps?
Do you think these changes are still ready to be merged?

**Comment by zecke** [comment]
I think the MongoTalk feature might be ready. For Voyage we would need to discuss how to use it. What might not be ready (or nice) is how to express the write concern. Out of the top of my head I don't know if my definition handles all cases.

**Comment by tinchodias** [comment]
I'm testing MongoCollection>>commandInsert:writeConcern: and commandDelete*. Delete is ok but Insert failed:
```
no such command: 'documents', bad cmd: '{ documents: [ { key: "value" } ], insert: "testCollection", $db: "test" }'
```
Sounds like "documents" key should be after "insert" key.

**Comment by tinchodias** [comment]
Yes, the ordering of the dictionary keys is important. I was a bit confused because the branch doesn't contain the new support for OrderedDictionary, but it's ok. It just needs to be rebased into current pharo-nosql's master. I can do it, and create a new PR. Good?

**Comment by zecke** [comment]
sure

**Pull request closed without merging**
