### PR TITLE
New in-image scripts

### PR DESCRIPTION
**Pull request by tinchodias**
Now starting a server is very handy, as this example code shows (available in class side of `MongoTestServer`):

~~~Smalltalk
	"Start"
	server := MongoTestServer new
				port: 27092;
				yourself.
	server start; waitIsWrittable.
	[[ 	[| isMaster |
		isMaster := server mongoDo: [ :mongo | mongo isMaster ].
		Transcript cr; show: isMaster localTime; cr]
			on: Error do: [ :e | e logCr ].
		1 second wait.
		] doWhileTrue: [ server isStarted ] ] fork.

	"Play"
	server sigstop. "pause"
	server sigcont. "unpause"

	"Stop"
	server ensureTerminated.
~~~

or this code:
~~~Smalltalk
replicaSet := MongoTestReplicaSet new
		addMember: 1 port: self mongoUrlA port priority: 5.0;
		addMember: 2 port: self mongoUrlB port priority: 3.0;
		addMember: 3 port: self mongoUrlC port priority: 0.0;
		startAllAndInitiate
~~~
(in `MongoReplicationTestResources class>>#start`)

### CODE REVIEW

**Comment by tinchodias** [comment]
Note about the word "Test" in the `MongoTestServer`:  This class (and `MongoTestReplicaSet` too) starts "real" `mongod` instances; I mean, they are not mocks or something like that only useful for testing. I used "Test" because I don't think they can be used with other purposes than creating testing scenarios or benchmarking.

**Comment by tinchodias** [comment]
I think this PR doesn't hurt any user. The only limitation I can see is that OSSubprocess doesn't support Windows AFAIK, yet.

**Comment by tinchodias** [comment]
I discovered a problem with this change: Voyage has the "multiple image tests", that install ImageWorker, that install OSProcess (CommandShell project), and it seems to be incompatible to have both in the same image (OSProcess and OSSubprocess).

My motivation to implement these MongoTestServer is to simplify signalling to the mongod processes and simulate in some way errors in replica set servers. The same can be done with OSProcess so... I will push these changes.

**Comment by tinchodias** [comment]
Any opinion, @estebanlm ?

**Comment by estebanlm** [comment]
Mmm. 
MMM...
I guess is fine for now. 
We need to find a way to make OSProcess and OSSubprocess to coexist.

**Comment by tinchodias** [comment]
Thanks! then I we can merge it.

**Pull request merged**
