### PR TITLE
Move replica set tests to 2 new packages

### PR DESCRIPTION
**Pull request by tinchodias**
**(Same as #97 but rebased and squashed to avoid merging conflicts and be more compact, too)**

Move the replica-set tests into new packages, so that the `Client` group doesn't require OSProcess either or OSSubprocess.

The groups named `Tests` and `Client` already existed, and I added 2 more with the `+ ReplicaSet Tests` suffix that involve loading the dependency.
```
				group: 'Tests' with: #('Mongo-Tests-BSON' 'Mongo-Tests-Core' 'Mongo-Tests-Queries');
				group: 'Tests + ReplicaSet Tests' with: #(Tests 'Mongo-Tests-ReplicaSet');
				group: 'Client' with: #('default' 'Mongo-Client' 'Mongo-Client-Tests');
				group: 'Client + ReplicaSet Tests' with: #('Client' 'Mongo-Client-ReplicaSet-Tests') ].
```

I changed CI to run on these 2 new groups.

See discussion in #96

### CODE REVIEW

**Comment by tinchodias** [comment]
@noha I didn't meant to abandon the conversation in #96 but anyway continued with the changes to split the packages. I was better to keep the other changes in one commit because then it's clear to see what changes from using OSProcess vs using OSSubprocess. 
If this PR is merged and project released, then Voyage shouldn't have tests from Mongotalk but excluding the replica set tests that require the process handling. And everybody should be happy again
.

**Review by noha — APPROVED** [review]

**Comment by noha** [comment]
Bravo! Thank you very much! Merged myself because it is blocking us ;)

**Comment by tinchodias** [comment]
Did you had the opportunity to test it in Voyage (using master)? 
Maybe before creating the tag...

**Comment by tinchodias** [comment]
offtopic, but I comment it here anyway: I removed this PR's branch, which I forgot to do in some occasions after merge. Also went to branchs tab and also 3 old branchs from mine + also 3 branches from you, Norbert. Now there is only master.

**Comment by noha** [comment]
Thanks. I clean branches from time to time myself. Cleaning/Removing is kind of a super power in IT only few have it ;)

**Pull request merged**
